
export const SUPABASE_URL = "https://mbxxehxzhxogqtzlzyvm.supabase.co"
export const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ieHhlaHh6aHhvZ3F0emx6eXZtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4NTA5MDg4NywiZXhwIjoyMDAwNjY2ODg3fQ.TVKcYE_aKBfBCFCjCCDEUxk_iZJeoTv_7_DXOlT_ks4"